server:
  port: 9003
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  servlet:
    context-path: /sso
spring:
  application:
    name: ssoModel
  #192.168.0.116
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mby?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&requireSSL=false
#    username: root
#    password: 68227597
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  messages:
    encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  mvc:
    favicon:
      enabled: false

#mybatis
mybatis:
  type-aliases-package: com.cloudColony.ssomodel.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  file: E:\\IDEA\\log\\ssoModel.log
  level:
    root: info
#    com:
#      mby:
#        myproject:
#          login:
#            controller: error
#          #          service: info
#          kuaidi:
#            controller: warn
  pattern:
    console: --%date{yyyy-MM-dd HH:mm:ss} %logger{0} - %msg%n
